from __future__ import annotations

from typing import Protocol
from uuid import UUID


class ObjectStorage(Protocol):
    def put(self, key: str, data: bytes, *, content_type: str) -> None: ...

    def get(self, key: str) -> bytes: ...

    def exists(self, key: str) -> bool: ...

    def delete(self, key: str) -> None: ...

    def generate_key(self, *, organization_id: UUID, namespace: str, name: str) -> str: ...
