export const copy = {
  skipToContent: "Saltar al contenido",
  appName: "BudgetLens",
  envLocal: "Local",
  envTest: "Pruebas",
  envDev: "Desarrollo",
  statusTitle: "Estado del sistema",
  statusDescription:
    "Comprueba que la API y la base de datos responden antes de trabajar con presupuestos.",
  checking: "Comprobando el estado del sistema",
  healthy: "Sistema listo",
  healthyDetail: "La API y la base de datos responden correctamente.",
  unavailable: "No se pudo comprobar el estado",
  unavailableDetail:
    "La API no respondió. Revisa que Docker esté en ejecución y vuelve a intentar.",
  degraded: "El sistema no está listo",
  degradedDetail: "La API responde, pero una dependencia necesaria no está disponible.",
  retry: "Reintentar",
  copyTrace: "Copiar identificador de seguimiento",
  copied: "Identificador copiado",
  traceLabel: "Identificador de seguimiento",
  apiLive: "API",
  database: "Base de datos",
  version: "Versión",
  available: "Disponible",
  ready: "Lista",
  error: "No disponible",
  unknown: "Sin comprobar",
  lastUpdated: "Última comprobación",
  commit: "commit",
  navStatus: "Estado",
  navCatalog: "Catálogo",
  catalogTitle: "Dimensiones y versiones",
  catalogDescription:
    "Revisa cuentas, departamentos, centros de costo y versiones de presupuesto de la organización activa.",
  selectUser: "Usuario local",
  selectOrganization: "Organización",
  chooseUser: "Selecciona un usuario",
  chooseOrganization: "Selecciona una organización",
  currencyLabel: "Moneda",
  fiscalStartLabel: "Inicio fiscal",
  accountsTitle: "Cuentas",
  departmentsTitle: "Departamentos",
  costCentersTitle: "Centros de costo",
  versionsTitle: "Versiones de presupuesto",
  emptyAccounts: "No hay cuentas para los filtros actuales.",
  emptyDepartments: "No hay departamentos para los filtros actuales.",
  emptyCostCenters: "No hay centros de costo para los filtros actuales.",
  emptyVersions: "No hay versiones de presupuesto.",
  code: "Código",
  name: "Nombre",
  type: "Tipo",
  status: "Estado",
  fiscalYear: "Año fiscal",
  active: "Activa",
  draft: "Borrador",
  published: "Publicada",
  archived: "Archivada",
  createAccount: "Crear cuenta",
  createDepartment: "Crear departamento",
  createCostCenter: "Crear centro de costo",
  createVersion: "Crear versión",
  publish: "Publicar versión",
  activate: "Activar versión",
  archive: "Archivar versión",
  confirmPublish: "Publicar deja esta versión inmutable. ¿Quieres continuar?",
  confirmActivate: "Esta versión quedará como la activa del año fiscal. ¿Quieres continuar?",
  confirmArchive: "La versión dejará de aparecer por defecto. ¿Quieres continuar?",
  catalogLoading: "Cargando el catálogo",
  catalogError: "No se pudo cargar el catálogo",
  sessionNeeded: "Selecciona un usuario y una organización para ver el catálogo.",
  roleLabel: "Rol",
} as const;
