export const copy = {
  skipToContent: "Saltar al contenido",
  appName: "BudgetLens",
  envLocal: "Local",
  envTest: "Pruebas",
  envDev: "Desarrollo",
  statusTitle: "Estado del sistema",
  statusDescription:
    "Comprueba que la API y la base de datos responden antes de trabajar con presupuestos.",
  checking: "Comprobando el estado del sistema",
  healthy: "Sistema listo",
  healthyDetail: "La API y la base de datos responden correctamente.",
  unavailable: "No se pudo comprobar el estado",
  unavailableDetail:
    "La API no respondió. Revisa que Docker esté en ejecución y vuelve a intentar.",
  degraded: "El sistema no está listo",
  degradedDetail: "La API responde, pero una dependencia necesaria no está disponible.",
  retry: "Reintentar",
  copyTrace: "Copiar identificador de seguimiento",
  copied: "Identificador copiado",
  traceLabel: "Identificador de seguimiento",
  apiLive: "API",
  database: "Base de datos",
  version: "Versión",
  available: "Disponible",
  ready: "Lista",
  error: "No disponible",
  unknown: "Sin comprobar",
  lastUpdated: "Última comprobación",
  commit: "commit",
  navStatus: "Estado",
  navCatalog: "Catálogo",
  navAnalyze: "Analizar",
  navDashboard: "Resumen",
  navVariances: "Variaciones",
  navPlan: "Planear",
  navScenarios: "Escenarios",
  navData: "Datos",
  navImports: "Importaciones",
  navAssist: "Asistir",
  navCopilot: "Copiloto",
  navAdmin: "Administrar",
  navSettings: "Configuración",
  navMembers: "Miembros",
  navOps: "Operación",
  openNavigation: "Abrir navegación",
  closeNavigation: "Cerrar navegación",
  collapseNavigation: "Contraer navegación",
  expandNavigation: "Expandir navegación",
  personaBudgetOwner: "Responsable de presupuesto",
  personaAnalyst: "Analista FP&A",
  personaAdmin: "Administrador",
  personaOperator: "Operador de plataforma",
  switchedOrganization: "Cambiaste a",
  sessionNeededDashboard: "Selecciona un usuario y una organización para ver el resumen.",
  sessionNeededGeneric: "Selecciona un usuario y una organización para continuar.",
  forbiddenTitle: "Esta vista no está disponible",
  forbiddenDetail: "Tu rol no incluye esta acción.",
  dashboardTitle: "Resumen",
  dashboardDescription:
    "Detecta desviaciones del año actual y abre la evidencia con el mismo alcance.",
  filterVersion: "Versión",
  filterPeriodFrom: "Periodo inicial",
  filterPeriodTo: "Periodo final",
  filterDepartment: "Departamento",
  filterAccount: "Cuenta",
  filterCostCenter: "Centro de costo",
  filterSort: "Orden",
  sortUnfavorable: "Mayor desviación desfavorable",
  sortVariance: "Importe de variación",
  resetFilters: "Restablecer filtros",
  chooseVersion: "Selecciona una versión",
  kpiBudget: "Presupuesto",
  kpiActual: "Real",
  kpiVariance: "Variación",
  kpiVariancePct: "Variación %",
  vsBudget: "vs presupuesto",
  trendTitle: "Tendencia mensual",
  topUnfavorableTitle: "Principales desviaciones desfavorables",
  breakdownTitle: "Desglose por departamento",
  emptyFigures: "No hay cifras para el alcance seleccionado.",
  emptyFiguresHint: "Importa actuals o publica una versión para comparar presupuesto y real.",
  importToCompare: "Ir a importaciones",
  exportView: "Exportar vista",
  exportDisabled: "No hay cifras para exportar con el alcance actual.",
  exportScopeTitle: "Alcance de la exportación",
  variancesTitle: "Variaciones",
  variancesDescription: "Ordena, profundiza y conserva el alcance en el recorrido.",
  breadcrumbHome: "Resumen",
  openDepartment: "Abrir departamento",
  openAccount: "Abrir cuenta",
  openCostCenter: "Abrir centro de costo",
  monthlyCompare: "Comparar tendencia mensual",
  importsTitle: "Importaciones",
  importsDescription:
    "Configura la organización, consulta la plantilla y prepara el archivo antes de aplicar datos.",
  createOrganization: "Crear organización",
  slugLabel: "Identificador corto",
  downloadTemplate: "Descargar plantilla",
  templateHint:
    "La plantilla usa periodo, cuenta, departamento, centro de costo, importe y moneda.",
  uploadFile: "Subir archivo",
  mapColumns: "Asignar columnas",
  previewTitle: "Vista previa",
  previewEmpty: "Aún no hay un archivo validado. El commit permanece deshabilitado.",
  commitImport: "Confirmar importación",
  commitBlocked: "El commit permanece deshabilitado mientras existan filas inválidas.",
  downloadErrors: "Descargar errores",
  downloadErrorsDisabled: "No hay un archivo de errores para descargar.",
  chooseFile: "Selecciona un archivo CSV o XLSX.",
  scenariosTitle: "Escenarios",
  scenariosDescription:
    "Define un cambio porcentual sobre un baseline. El cálculo usa el motor determinista.",
  scenarioName: "Nombre del escenario",
  baselineLabel: "Baseline",
  percentChange: "Cambio porcentual",
  futureMonths: "Meses futuros",
  previewImpact: "Calcular impacto",
  saveScenario: "Guardar escenario",
  compareScenario: "Comparar con baseline",
  emptyScenarioImpact: "No hay un baseline con cifras para calcular el impacto total y mensual.",
  copilotTitle: "Copiloto",
  copilotDescription:
    "Pregunta sobre el alcance visible. El contexto se envía como filtros, no como texto libre.",
  copilotPlaceholder: "¿Qué explica el exceso de gasto de operaciones?",
  askCopilot: "Preguntar",
  viewEvidence: "Ver evidencia",
  hideEvidence: "Ocultar evidencia",
  evidenceTitle: "Evidencia",
  evidenceEmpty: "Aún no hay herramientas ni filas agregadas para esta pregunta.",
  contextTitle: "Contexto de la vista",
  copilotUnavailable:
    "El copiloto necesita datos analíticos autorizados para responder con evidencia.",
  settingsTitle: "Organización",
  settingsDescription:
    "Moneda funcional, comienzo fiscal y retención de conversaciones de la organización activa.",
  conversationRetentionLabel: "Retención de conversaciones (días)",
  saveOrganization: "Guardar organización",
  membersTitle: "Miembros",
  membersDescription: "Administra quién pertenece a la organización y con qué rol.",
  addMember: "Agregar miembro",
  emptyMembers: "No hay miembros para mostrar.",
  opsTitle: "Operación",
  opsDescription:
    "Consulta disponibilidad, versión y un identificador de seguimiento. Esta vista no muestra cifras financieras.",
  traceLookup: "Identificador de seguimiento",
  traceLookupHint:
    "Usa el identificador en los registros de la aplicación. Los registros no incluyen contenido financiero.",
  appVersionLabel: "Versión de la aplicación",
  noOrganizations: "Este usuario no pertenece a ninguna organización.",
  chooseAll: "Todos",
  catalogTitle: "Dimensiones y versiones",
  catalogDescription:
    "Revisa cuentas, departamentos, centros de costo y versiones de presupuesto de la organización activa.",
  selectUser: "Usuario local",
  selectOrganization: "Organización",
  chooseUser: "Selecciona un usuario",
  chooseOrganization: "Selecciona una organización",
  currencyLabel: "Moneda",
  fiscalStartLabel: "Inicio fiscal",
  accountsTitle: "Cuentas",
  departmentsTitle: "Departamentos",
  costCentersTitle: "Centros de costo",
  versionsTitle: "Versiones de presupuesto",
  emptyAccounts: "No hay cuentas para los filtros actuales.",
  emptyDepartments: "No hay departamentos para los filtros actuales.",
  emptyCostCenters: "No hay centros de costo para los filtros actuales.",
  emptyVersions: "No hay versiones de presupuesto.",
  code: "Código",
  name: "Nombre",
  type: "Tipo",
  status: "Estado",
  fiscalYear: "Año fiscal",
  active: "Activa",
  draft: "Borrador",
  published: "Publicada",
  archived: "Archivada",
  createAccount: "Crear cuenta",
  createDepartment: "Crear departamento",
  createCostCenter: "Crear centro de costo",
  createVersion: "Crear versión",
  publish: "Publicar versión",
  activate: "Activar versión",
  archive: "Archivar versión",
  confirmPublish: "Publicar deja esta versión inmutable. ¿Quieres continuar?",
  confirmActivate: "Esta versión quedará como la activa del año fiscal. ¿Quieres continuar?",
  confirmArchive: "La versión dejará de aparecer por defecto. ¿Quieres continuar?",
  catalogLoading: "Cargando el catálogo",
  catalogError: "No se pudo cargar el catálogo",
  sessionNeeded: "Selecciona un usuario y una organización para ver el catálogo.",
  roleLabel: "Rol",
  importType: "Tipo de importación",
  importBudget: "Presupuesto",
  importActual: "Real",
  validating: "Validando archivo",
  importReady: "El archivo está listo para confirmar.",
  importInvalid: "Hay filas que debes corregir antes de confirmar.",
  importApplied: "La importación se aplicó correctamente.",
  importFailed: "No se pudo completar la importación.",
  loadingFigures: "Calculando cifras del alcance",
  figuresError: "No se pudieron cargar las cifras.",
  favorable: "Favorable",
  unfavorable: "Desfavorable",
  neutral: "Neutral",
  unknownFavorability: "Sin clasificar",
  cancelImport: "Cancelar importación",
  errorCorrective: "Revisa los datos, corrige lo indicado e inténtalo de nuevo.",
  copilotWorking: "El copiloto sigue trabajando…",
  copilotStillWorking: "La consulta continúa. Puedes esperar o salir sin perder el contexto.",
  importWorking: "Validando el archivo. El proceso continúa…",
  metricsTitle: "Métricas técnicas",
  metricsEmpty: "Aún no hay muestras de latencia en este proceso.",
  requestsLabel: "Solicitudes",
  jobsTimedOut: "Trabajos con tiempo agotado",
  aiRuns: "Ejecuciones de copiloto",
  estimatedCost: "Costo estimado",
  costNotConfigured: "Sin tabla de precios configurada",
} as const;
