export const copy = {
  skipToContent: "Saltar al contenido",
  appName: "BudgetLens",
  envLocal: "Local",
  envTest: "Pruebas",
  envDev: "Desarrollo",
  statusTitle: "Estado del sistema",
  statusDescription:
    "Comprueba que la API y la base de datos responden antes de trabajar con presupuestos.",
  checking: "Comprobando el estado del sistema",
  healthy: "Sistema listo",
  healthyDetail: "La API y la base de datos responden correctamente.",
  unavailable: "No se pudo comprobar el estado",
  unavailableDetail:
    "La API no respondió. Revisa que Docker esté en ejecución y vuelve a intentar.",
  degraded: "El sistema no está listo",
  degradedDetail: "La API responde, pero una dependencia necesaria no está disponible.",
  retry: "Reintentar",
  copyTrace: "Copiar identificador de seguimiento",
  copied: "Identificador copiado",
  traceLabel: "Identificador de seguimiento",
  apiLive: "API",
  database: "Base de datos",
  version: "Versión",
  available: "Disponible",
  ready: "Lista",
  error: "No disponible",
  unknown: "Sin comprobar",
  lastUpdated: "Última comprobación",
  commit: "commit",
} as const;
